version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - konecta_network
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - konecta_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - konecta_network

networks:
  konecta_network:
    driver: bridge

volumes:
  pgdata:
